### ISSUE TITLE
Revisar latlng

### ISSUE THREAD

**Issue by rgaiacs** [dani-lbnl/2015-06-19-labvis#5]
Utilizamos o campo `latlng` para o mapa de direções e para http://software-carpentry.org/workshops. Eu coloquei coordenadas genéricas de Fortaleza em 66a8f79785b14084c439bf8c56a335c6587ccbad mas é bom trocar por outras mais precisas.

**Comment by dani-lbnl** [comment]
Expectation: within 7 days

**Comment by rgaiacs** [comment]
@dani-lbnl Você pode me obter coordenadas precisas para

> LABVIS - Laboratório de Visão, Imagens e Sinais
> Bloco 710 - Campus do PICI - Fortaleza-CE - CEP 60450-360
