### ISSUE TITLE
Agradecimentos

### ISSUE THREAD

**Issue by rgaiacs** [dani-lbnl/2015-06-19-labvis#6]
Em 30abce35e830454dd9cbb6d9a6c5cccee33e175b eu melhorei um pouco os agradecimentos. Encontrei um logo em http://www.gpi.ufc.br/index.html. Posso deixá-lo ou preciso trocá-lo?

**Comment by dani-lbnl** [comment]
I like this logo better:
http://www.gpi.ufc.br/workvolpato/images/logo_gpi_big.gif

**Comment by rgaiacs** [comment]
Corrigido em 470999d57856327bbc4fa306444382da11f64e54.
