### ISSUE TITLE
Eventbrite

### ISSUE THREAD

**Issue by rgaiacs** [dani-lbnl/2015-06-19-labvis#7]
Em 2b71734f1244c1e414f9927e655659dc37bd7cc6 eu adicionei o código do Eventbrite. Podemos não utilizá-lo, só preciso ser notificado para remover o [evento no Eventbrite](https://www.eventbrite.com/e/bilhetes-workshop-da-software-carpentry-na-universidade-federal-do-ceara-16989573271).

**Comment by dani-lbnl** [comment]
Registrei-me e cada vez q retorno a inscricao contabilizou uma vez --- tem como evitar que a mesma pessoa registre-se mais de uma vez?

**Comment by dani-lbnl** [comment]
Outros problemas: (a) o horario esta incorreto; (b) nro de pessoas = 30 (sala comporta ateh 30 pessoas)

**Comment by dani-lbnl** [comment]
We intend to have a waiting list of ~ 10 people, what you think?

**Comment by rgaiacs** [comment]
> tem como evitar que a mesma pessoa registre-se mais de uma vez? 

Não.

> o horario esta incorreto

Corrigido.

> nro de pessoas = 30

Corrigido

> We intend to have a waiting list of ~ 10 people, what you think?

Habilitado lista de espera.
